# Generated by Django 4.1.2 on 2022-11-07 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDCModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vdc_uuid', models.UUIDField()),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StorageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storage_uuid', models.UUIDField()),
                ('type', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('vdc_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.vdcmodel')),
            ],
        ),
    ]
