# Generated by Django 4.1.2 on 2022-11-07 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_vdcmodel_storagemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemodel',
            name='vdc_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vdc', to='women.vdcmodel', to_field='vdc_uuid'),
        ),
        migrations.AlterField(
            model_name='vdcmodel',
            name='vdc_uuid',
            field=models.UUIDField(unique=True),
        ),
    ]
