# Generated by Django 4.1.2 on 2022-11-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_storagemodel_vdc_uuid_alter_vdcmodel_vdc_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagemodel',
            name='vdc_uuid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.vdcmodel'),
        ),
    ]
