# Generated by Django 4.1.2 on 2022-11-07 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0004_alter_storagemodel_vdc_uuid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StorageModel',
            new_name='Storage',
        ),
        migrations.RenameModel(
            old_name='VDCModel',
            new_name='VDC',
        ),
    ]
