# Generated by Django 4.1.2 on 2022-11-07 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0005_rename_storagemodel_storage_rename_vdcmodel_vdc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='VDC',
        ),
    ]
