# Generated by Django 4.1.2 on 2022-11-07 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0006_delete_storage_delete_vdc'),
    ]

    operations = [
        migrations.CreateModel(
            name='VDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('vdc_uuid', models.UUIDField(unique=True)),
                ('site', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('storage_uuid', models.UUIDField()),
                ('type', models.CharField(max_length=50)),
                ('volume', models.IntegerField()),
                ('vdc_uuid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vdc', to='women.vdc')),
            ],
        ),
    ]
