# Generated by Django 4.1.3 on 2022-11-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0007_vdc_storage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Storage',
        ),
        migrations.DeleteModel(
            name='VDC',
        ),
    ]
