# Generated by Django 4.1.3 on 2022-11-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0009_category_women_cat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='women',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Famous woman', 'verbose_name_plural': 'Famous woman'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Category'),
        ),
    ]
